[package]
name = "framy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
kamadak-exif = "0.5.5"
photon-rs = "0.3.2"
